# Dependencies
markdown:         kramdown
redcarpet:
 extensions: ["fenced_code_blocks", "autolink", "tables"]

highlighter: rouge



# Permalinks
permalink:        pretty

# Setup
title:            utwiddle
tagline:          'Ubiquitous URN twiddling'
description:      ''
#baseurl: http://neelsmith.github.io
baseurl: ""






links:
  - title: Github source repository
    url: https://github.com/neelsmith/utwiddle
    external: true
